### ISSUE TITLE
Token/ Key 관련 보안 이슈 

### ISSUE THREAD

**Issue by Oizys18** [soulgchoi/TIL#3]
soulgchoi/TIL › 00_startcamp/day04.md
> Line 298, 329, 342 : token 값 노출 

soulgchoi/TIL › 00_startcamp/day04/second_flask/app.py
> Line 61 : token 값 노출 

soulgchoi/TIL › 00_startcamp/day04/stock/stock.py
> Line 21 : token 값 노출

soulgchoi/TIL › 09_JS/02_giphySearchEngine/main.js
> Line 10 : API_KEY 노출 
> Line 60 : API_KEY 노출 

심각한 보안 문제가 발생할 수 있으니 환경변수로 관리해주세요 ^ ^

**Comment by soulgchoi** [comment]
수정했습니다. 압도적 감사^^
